<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions 
	name="dealernetworkService"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
	xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" 
	xmlns:sd="urn:org.soitoolkit.refapps.dealernetwork.createorder.schema:v1"
	xmlns="urn:org.soitoolkit.refapps.dealernetwork.createorder.wsdl:v1" 
	targetNamespace="urn:org.soitoolkit.refapps.dealernetwork.createorder.wsdl:v1">


	<wsdl:types>
		<xsd:schema>
			<xsd:import 
				namespace="urn:org.soitoolkit.refapps.dealernetwork.createorder.schema:v1"
            	schemaLocation="CreateOrder.xsd"/>
		</xsd:schema>
	</wsdl:types>


	<wsdl:message name="createOrderRequest">
		<wsdl:part name="parameters" element="sd:createOrder" />
	</wsdl:message>
	<wsdl:message name="createOrderResponse">
		<wsdl:part name="parameters" element="sd:createOrderResponse"/>
	</wsdl:message>

	
    <wsdl:message name="Fault">
       <wsdl:part name="fault" element="sd:faultInfo"/>
    </wsdl:message>
	
	<wsdl:portType name="createOrderInterface">
		<wsdl:operation  name="createOrder">
			<wsdl:input  message="createOrderRequest"/>
			<wsdl:output message="createOrderResponse"/>
			<wsdl:fault name="fault" message="Fault"/>
		</wsdl:operation>

	</wsdl:portType>
	
	<wsdl:binding name="createOrderBinding" type="createOrderInterface">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>


		<wsdl:operation name="createOrder">
			<soap:operation soapAction="urn:org.soitoolkit.refapps.dealernetwork.createorder.wsdl:v1:createOrder"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
            <wsdl:fault name="fault">
                <soap:fault use="literal" name="fault"/>
            </wsdl:fault>
		</wsdl:operation>

	</wsdl:binding>

	<wsdl:service name="createOrderService">
		<wsdl:port name="createOrderPort" binding="createOrderBinding">
			<soap:address location="http://localhost:8080/services/createorder/v1"/>
		</wsdl:port>
	</wsdl:service>

</wsdl:definitions>