/**
 * This file was automatically generated by the Mule Development Kit
 */
package org.soitoolkit.commons.studio.components;

import org.mule.api.annotations.Module;
import org.mule.api.ConnectionException;
import org.mule.api.annotations.Configurable;
import org.mule.api.annotations.Processor;

/**
 * Generic module
 *
 * @author MuleSoft, Inc.
 */
@Module(name="soitoolkit", schemaVersion="0.5.1-SNAPSHOT")
public class soitoolkitModule
{
    /**
     * Configurable
     */
    @Configurable
    private String myProperty;

    /**
     * Set property
     *
     * @param myProperty My property
     */
    public void setMyProperty(String myProperty)
    {
        this.myProperty = myProperty;
    }

    /**
     * Get property
     */
    public String getMyProperty()
    {
        return this.myProperty;
    }

    /**
     * Custom processor
     *
     * {@sample.xml ../../../doc/soitoolkit-connector.xml.sample soitoolkit:my-processor}
     *
     * @param content Content to be processed
     * @return Some string
     */
    @Processor
    public String myProcessor(String content)
    {
        /*
         * MESSAGE PROCESSOR CODE GOES HERE
         */
    	System.err.println("### MY COMP WORKS!");
        return content;
    }
}
